<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container21RKw7x\Shopware_Production_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container21RKw7x/Shopware_Production_KernelProdContainer.php') {
    touch(__DIR__.'/Container21RKw7x.legacy');

    return;
}

if (!\class_exists(Shopware_Production_KernelProdContainer::class, false)) {
    \class_alias(\Container21RKw7x\Shopware_Production_KernelProdContainer::class, Shopware_Production_KernelProdContainer::class, false);
}

return new \Container21RKw7x\Shopware_Production_KernelProdContainer([
    'container.build_hash' => '21RKw7x',
    'container.build_id' => '1ef9452e',
    'container.build_time' => 1682598396,
], __DIR__.\DIRECTORY_SEPARATOR.'Container21RKw7x');
