<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXR1cOoc\Shopware_Core_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXR1cOoc/Shopware_Core_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerXR1cOoc.legacy');

    return;
}

if (!\class_exists(Shopware_Core_KernelProdContainer::class, false)) {
    \class_alias(\ContainerXR1cOoc\Shopware_Core_KernelProdContainer::class, Shopware_Core_KernelProdContainer::class, false);
}

return new \ContainerXR1cOoc\Shopware_Core_KernelProdContainer([
    'container.build_hash' => 'XR1cOoc',
    'container.build_id' => '59c517b9',
    'container.build_time' => 1682601981,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXR1cOoc');
