name: DEV Deployment

on:
  push:
    paths:
      - 'src/public/**'
    branches:
    - 'development'

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checking out the repo
      uses: actions/checkout@v2

    - name: Install composer      
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        pwd
        mkdir ~/.ssh
        echo -e "${SSH_KEY}" >~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        cd ./src/public && composer install
    
    - name: Build PM Docker Image
      uses: pmagentur/pm_docker_builder@v0.2
      env:
        USERNAME: ${{ secrets.Docker_user }}
        PASSWORD: ${{ secrets.Docker_pass }}
        REGISTRY: docker.dev01.pmagentur.com
        REPOSITORY: ${{ secrets.DOCKER_REPOSITORY }}
        TAG: 'dev' 
        DOCKERFILE_PATH: 'src/.'
        CREATE_BACKUP: 'True'
